version: '3.9'
services:
    database:
        container_name: genealogy_db
        image: mysql:8.0.30-oracle
        cap_add:
            - SYS_NICE
        restart: always
        ports:
            - '${MYSQL_PORT}:${MYSQL_PORT}'
        volumes:
            - db:/var/lib/mysql
        env_file:
            - .env
    app:
        container_name: api
        build:
            dockerfile: Dockerfile
            context: .
            target: dev
        depends_on:
            - '${MYSQL_HOST}'
        networks:
            - default
        volumes:
            - .:/opt/app/api
        ports:
            - '${API_PORT}:${API_PORT}'
        env_file:
            - .env
volumes:
    db:
    app: