version: '3.9'
networks:
    genealogy_network:
        driver: bridge
services:
    database:
        container_name: genealogy_db
        build:
            context: .
            dockerfile: .docker/db/Dockerfile
        env_file:
            - .env
        ports:
            - '${MYSQL_PORT}:${MYSQL_PORT}'
        volumes:
            - .:/opt/app/api
        command: ['--log_bin_trust_function_creators=1']
        networks:
            - genealogy_network
    app:
        container_name: api
        build:
            dockerfile: .docker/api/Dockerfile
            context: .
            target: dev
        env_file:
            - .env
        depends_on:
            - '${MYSQL_HOST}'
        networks:
            - genealogy_network
        volumes:
            - .:/opt/app/api
        ports:
            - '${API_PORT}:${API_PORT}'
        environment:
            - WAIT_HOSTS=database:3306
volumes:
    database:
    app: